[phases.setup]
nixPkgs = ["python311", "SDL2", "SDL2_image", "SDL2_mixer", "SDL2_ttf"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120"
